apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exam-prep
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: "equiz_db"
  POSTGRES_USER: "equiz_user"
  POSTGRES_PASSWORD: "equiz@123.com"
